
spring.application.name: student_grade_management

server:
   servlet.context-path: /student_grade_management/api/v1
   port: 8080
   address: localhost

#datasource conf
spring.datasource:
   url: jdbc:postgresql://localhost:5432/student_grade_management_db
   driver-class-name: org.postgresql.Driver
   username: postgres
   password: 45678

#jpa - hibernate conf
spring.jpa:
   sql.init.mode: always
   show-sql: true
   properties.hibernate:
      format_sql: true
      validator:
         apply_to_ddl: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      globally_quoted_identifiers: true
   generate-ddl: true
   hibernate.ddl-auto: update


spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

apiMajorVersion: 1
apiMinorVersion: 1

